/**
 * Regenerates the canonical_items seed migration from src/lib/taxonomy/canonical-items.ts.
 *
 *   pnpm taxonomy:gen                 # writes a new timestamped migration
 *   pnpm taxonomy:gen 20260903000004  # writes/overwrites a specific version (initial seed)
 *
 * The upsert is idempotent, so re-running against an existing DB is safe.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CANONICAL_ITEMS } from '../src/lib/taxonomy/canonical-items';

const esc = (s: string) => s.replace(/'/g, "''");
const version = process.argv[2] ?? new Date().toISOString().replace(/\D/g, '').slice(0, 14);
const outDir = join(process.cwd(), 'supabase', 'migrations');
const outFile = join(outDir, `${version}_canonical_items_seed.sql`);

const rows = CANONICAL_ITEMS.map((i, idx) => {
  const aliases = i.aliases.length ? `array[${i.aliases.map((a) => `'${esc(a)}'`).join(',')}]::text[]` : `'{}'::text[]`;
  return `  ('${esc(i.slug)}', '${esc(i.displayName)}', '${esc(i.category)}', '${i.businessCategory}', '${i.comparableUnit}', ${aliases}, ${idx})`;
});

const sql = `-- GENERATED by scripts/gen-taxonomy-migration.ts from src/lib/taxonomy/canonical-items.ts. Do not edit by hand.
insert into public.canonical_items (slug, display_name, category, business_category, comparable_unit, aliases, sort_order) values
${rows.join(',\n')}
on conflict (slug) do update set
  display_name = excluded.display_name,
  category = excluded.category,
  business_category = excluded.business_category,
  comparable_unit = excluded.comparable_unit,
  aliases = excluded.aliases,
  sort_order = excluded.sort_order;
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, sql);
console.log(`wrote ${outFile} (${CANONICAL_ITEMS.length} items)`);
